### ISSUE TITLE
Redirect not working since update to 2.1.8

### ISSUE THREAD

**Issue by lavitto-private** [pfpayments/woocommerce#14]
Since the update to version 2.1.8, the redirection to the PostFinance checkout no longer works.

Instead of the redirection, the JSON response is shown in the browser:

```
{"result": "success", "postfinancecheckout": "true", "redirect": "https:\/\/checkout.postfinance.ch\/s\/XXXXX\/payment\/transaction\/pay\/XXXXX"}
```
_XXXXX stands for the transaction ID and the securityToken, I removed that here._

When comparing versions, I noticed that changes were made in the appropriate place (includes/class-wc-postfinancecheckout-gateway.php). With a downgrade to 2.1.7 I could solve the error.

WordPress: 6.1.1
WooCommerce: 7.5.1
PHP: 8.0

**Comment by theodorspringwallee** [comment]
Dear [lavitto-private](https://github.com/lavitto-private)

In newer versions like WooCommerce 7.5.1 we redirect directly to the payment page instead of the other integrations.
So e.g. if you use "lightbox" integration it will redirect to payment page.

You probably use in your shop the "iframe" integration?
Because of this is a BUG reported, where we are working for. 

But if you choose "lightbox" as integration, the payment should work in the newest version.

Best regards

**Comment by lavitto-private** [comment]
Thanks for your feedback. Yes, we had the iFrame integration active and have now adjusted it to Lightbox. It worked in my test, however there are still customers with issues (we have cleared cache).

**Comment by theodorspringwallee** [comment]
Dear [lavitto-private](https://github.com/lavitto-private)

We are working on the fix, if released you also see it on: https://github.com/pfpayments/woocommerce/releases

Best regards

**Comment by masteradhoc** [comment]
@theodorspringwallee still no fix on this even after one month? we have same issue....

**Comment by masteradhoc** [comment]
@theodorspringwallee any update?

**Comment by marcostalder85** [comment]
@theodorspringwallee any updates?! still not working here too...

**Comment by theodorspringwallee** [comment]
Dear [masteradhoc](https://github.com/masteradhoc), @[marcostalder85](https://github.com/marcostalder85)
marcostalder85

Sorry, this git issue was going under. Nevertheless, the fix is already available, respectively was published by our developers (in previous versions).

In case it still does not work in the newest plugin version for you, please contact the PF support to let check this individually: https://www.postfinance.ch/de/support/hotline.html


Best regards
