### ISSUE TITLE
Error with bundled products in WooCommerce

### ISSUE THREAD

**Issue by kbverlag** [pfpayments/woocommerce#23]
There appears to be an error with bundled products in WooCommerce. The plugin is attempting to get a discount of an object that does not exist as expected:

```
Fatal error: Uncaught TypeError: Argument 1 passed to
WC_PostFinanceCheckout_Packages_Coupon_Discount::get_coupon_perc entage_discount_by_item) must be of the type string, null given, called in .../wp-includes/class-wp-hook.php on line 308 and defined in …/wp-content/plugins/woo-postfinance-checkout/includes/packages/coupon/class-wc-postfinancecheckout-
packages-coupon-discount.php:158
```

WordPress 6.2.2 v
WooCommerce: 7.7.0
PostFinance Checkout: 2.1.17

This is already the third error we report in a few weeks.

**Comment by theodorspringwallee** [comment]
Dear [kbverlag](https://github.com/kbverlag)

Thanks for your input.

Are you using the following plugin for the bundled products? https://woocommerce.com/de-de/products/product-bundles/ (respectively this setup: https://iconicwp.com/blog/create-product-bundles-in-woocommerce/)
In this case we can open a feature request, to add compatibility with our plugin

If you do this directly with the basis functionality within WooCommerce, please can you provide us reproduction steps?

Many thanks for your feedback.

Best regards

**Comment by kbverlag** [comment]
Thank you for the quick reply. We use the following plugin:

https://woocommerce.com/de-de/products/composite-products/ 

We think everything seems to have worked until the last update...

Best regards

**Comment by theodorspringwallee** [comment]
Dear [kbverlag](https://github.com/kbverlag)

Thanks for your reply.

Our plugin team will check this and will come back with feedback.

Best regards

**Comment by kbverlag** [comment]
As far as I can see, it's not so much about compatibility with a plugin, but more about querying the discount of an item in the shopping cart only if it is a valid object and has a discount.

**Comment by theodorspringwallee** [comment]
Dear [kbverlag](https://github.com/kbverlag)

According to our developers, if you can give us a license of that plugin to test, we can do further investigations on it.

I also checked the method changes in `get_coupon_percentage_discount_by_item()` in the file `class-wc-postfinancecheckout-packages-coupon-discount.php`:

What I saw that the filter `wc_postfinancecheckout_coupon_discounts_applied_by_cart` was replaced with `wc_postfinancecheckout_packages_coupon_discounts_applied_by_cart`:

```
$coupon_discounts_applied = apply_filters( 'wc_postfinancecheckout_packages_coupon_discounts_applied_by_cart', WC()->cart );
```

But this change is from March. Else for this method nothing there was changed, since March.

Which was your previous plugin version?

Best Regards

**Comment by kbverlag** [comment]
In fact, we have not sold this type of product since the end of March. Most likely, the issue has been for a longer period of time. Our programmer will take a close look tomorrow.

**Comment by E1NSER** [comment]
> Dear [kbverlag](https://github.com/kbverlag)
> 
> According to our developers, if you can give us a license of that plugin to test, we can do further investigations on it.
> 
> I also checked the method changes in `get_coupon_percentage_discount_by_item()` in the file `class-wc-postfinancecheckout-packages-coupon-discount.php`:
> 
> What I saw that the filter `wc_postfinancecheckout_coupon_discounts_applied_by_cart` was replaced with `wc_postfinancecheckout_packages_coupon_discounts_applied_by_cart`:
> 
> ```
> $coupon_discounts_applied = apply_filters( 'wc_postfinancecheckout_packages_coupon_discounts_applied_by_cart', WC()->cart );
> ```
> 
> But this change is from March. Else for this method nothing there was changed, since March.
> 
> Which was your previous plugin version?
> 
> Best Regards

I suppose I have identified and fixed the bug for the problem. Since there is unfortunately no possibility for a "Pull Request" on the repo, I try to explain the solution briefly:

https://github.com/pfpayments/woocommerce/blob/443ac7da767c9898dee77eaeb23cb043c2aa9dec/includes/packages/coupon/class-wc-postfinancecheckout-packages-coupon-discount.php#L158

In this function "$item_key" is expected as "string". For various product types which have a parent element, this value does not exist and is "null". However, since the function explicitly expects this type, it fails. If we now change `string $item_key` to `?string $item_key`, "null" is also possible next to "string" but the function can at least be called.

At that point where it comes to the final processing of "$item_key",

https://github.com/pfpayments/woocommerce/blob/443ac7da767c9898dee77eaeb23cb043c2aa9dec/includes/packages/coupon/class-wc-postfinancecheckout-packages-coupon-discount.php#L162

we can now check if the passed value exists and if it is of type "string".

**The fixed function:**

```php
public static function get_coupon_percentage_discount_by_item(?string $item_key)
  {
    $coupon_discounts_applied   = apply_filters('wc_postfinancecheckout_packages_coupon_discounts_applied_by_cart', WC()->cart);
    $coupon_percentage_discount = 0;
    foreach ($coupon_discounts_applied as $discounts) {
      // Check if the item key exists and is a string
      if (isset($discounts[ $item_key ]) && is_string($discounts[ $item_key ])) {
        $coupon_percentage_discount += $discounts[ $item_key ];
      }
    }
    return $coupon_percentage_discount;
   }
``` 

I would ask you to check if this modification is ok for you. The error here is not necessarily due to the plugin "[Composite Products](https://woocommerce.com/de-de/products/composite-products/)" but would occur with any element in the cart where there is no item_key of type "string".

**Comment by theodorspringwallee** [comment]
Dear [E1NSER](https://github.com/E1NSER)

Thanks for your inquiry.

We did in the meanwhile a patch for coupons within https://github.com/pfpayments/woocommerce/blame/754d84f5057678acf01b2188a3f17abf2de9630c/includes/service/class-wc-postfinancecheckout-service-line-item.php#L89

We try to cover your specific use case (in [class-wc-postfinancecheckout-packages-coupon-discount.php](https://github.com/pfpayments/woocommerce/blob/443ac7da767c9898dee77eaeb23cb043c2aa9dec/includes/packages/coupon/class-wc-postfinancecheckout-packages-coupon-discount.php#L162) ) within the next 2-3 weeks.

Best regards

**Comment by E1NSER** [comment]
@theodorspringwallee It has been 2 weeks now. Is there already news to move forward?

**Comment by theodorspringwallee** [comment]
Dear [E1NSER](https://github.com/E1NSER)

According to our product owner, we should have fixed this within the next 2 weeks (within this developer sprint).

Best regards

**Comment by E1NSER** [comment]
@theodorspringwallee It's been another 2 weeks since your last reply. What about a fix?

**Comment by theodorspringwallee** [comment]
Dear [E1NSER](https://github.com/E1NSER)

I have discussed this again with our developers, after their reproductions.

Unfortunately, we can't reproduce your issue on our environments.

It seems to be an individual issue, we can't reproduce in our standard environment.

Therefore to get further help, please contact the PostFinance support: https://www.postfinance.ch/de/support/hotline.html

Best regards

**Comment by theodorspringwallee** [comment]
Dear [E1NSER](https://github.com/E1NSER)

Is this Git Issue is still a topic for you?

Our developer did some general adjustments to improve our plugin's compatibility.

So if you are still interested into it, please can you send us a license of this Composite Products plugin, that we can test against our plugin?

Many thanks for your answer.

Best regards
