### ISSUE TITLE
Testing in .local environments

### ISSUE THREAD

**Issue by marcostalder85** [pfpayments/woocommerce#30]
Creating new websites with payment should be possible to do in ".local" areas for testing. We get some errors about the URLs if we try to work local. There should be a way to test and work local.

**Comment by theodorspringwallee** [comment]
Dear [marcostalder85](https://github.com/marcostalder85)

Please, can you describe the specific error you receive?

In general, the local running (e.g., via Docker) is not a problem. Furthermore, our plugins are developed in that way.

In case your issue is with the receiving of webhooks from the PFC portal, you need to use NGROK, to be able to receive the webhooks in local environments.

If you mean another issue, please let us know.

Best regards

**Comment by marcostalder85** [comment]
NGROK was the solution, thanks!
