### ISSUE TITLE
Chosen Payment forms are hidden

### ISSUE THREAD

**Issue by huntersbest** [pfpayments/woocommerce#36]
If user is logged in, Postfinance Card fields are invisible (style="position: absolute; left: -100000px") when payment method is chosen. Credit/Debitcard fields are ok

I user is NOT logged in all fields for any chosen payment methods are hidden. So no payment possible

**Comment by theodorspringwallee** [comment]
Dear [huntersbest](https://github.com/huntersbest)

We can confirm, that we are set the payment form to "left: -100000px" ("display:none leads to issues") in case of the PostFinance Card payment method because this payment method does not require input fields on the shop: https://github.com/pfpayments/woocommerce/blob/3e9c43bea4fae842c0a784729cdccd1153b9d3ba/assets/js/frontend/checkout.js#L176

The PostFinance Card method should redirect you directly to the payment page and does not support iframe/lightbox integrations on the shop.

If the redirection to the payment page does not work in your case please contact the PF Support: https://www.postfinance.ch/de/support/hotline.html

Best regards
