### ISSUE TITLE
plugin has been closed

### ISSUE THREAD

**Issue by tobinski** [pfpayments/woocommerce#4]
The plugin is not available over the wordpress plugin system. On https://wordpress.org/plugins/woo-postfinance-checkout/#description you can read the following message.

```
This plugin has been closed as of September 5, 2022 and is not available for download. This closure is temporary, pending a full review.
```

![plugin](https://user-images.githubusercontent.com/501804/193568734-f2dde404-81a1-474f-9a0e-84681898b1b6.png)

Whats the problem? When will the plugin available again? I like to use the plugin to migrate to the new postfinance psp system.

**Comment by theodorspringwallee** [comment]
Dear [tobinski](https://github.com/tobinski)

We are working on this. In the meanwhile, please use the download of this repository.

**Comment by theodorspringwallee** [comment]
Dear [masteradhoc](https://github.com/masteradhoc), because of the specific WordPress Marketplace coding guidelines, it will take still a long time, till our plugin is fully rewritten for the WordPress Store.

I really would recommend you to get newer plugin versions over this git repository in the meanwhile and upload it manually in the WordPress plugin menu in the backend: https://github.com/pfpayments/woocommerce

**Comment by masteradhoc** [comment]
@tobinski is now available again!

**Comment by theodorspringwallee** [comment]
Thanks [masteradhoc](https://github.com/masteradhoc), 

Yes the plugin is now back in the WordPress marketplace.

Many thanks for your patience.

I'll close now this Git Issue ticket.
